Add Pod Security Policies feature
puppetlabs/puppetserver-helm-chart pull request #109
Opened 2022-05-20 13:20 UTC by davidphayanouvong

Add Pod Security Policies feature

2022-05-20 16:45 UTC, Xtigyro requested changes
Thanks for the contribution, @davidphayanouvong! 🥇

Could you please update the `CHANGELOG.md` following the same pattern for previous releases and bump the minor chart version in `Chart.yaml`?

I've also requested a few other very minor changes.

Ah, yeah - finally, you might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)? 🥇

2022-05-20 16:45 UTC, Xtigyro commented on templates/puppetdb-podsecuritypolicy.yaml
> +{{- end }}
Could you please add an empty line here as EOF?

2022-05-20 16:45 UTC, Xtigyro commented on templates/puppetdb-role.yaml
> +{{- end }}
Could you please add an empty line here as EOF?

2022-05-20 16:45 UTC, Xtigyro commented on templates/puppetdb-rolebinding.yaml
> +{{- end }}
Could you please add an empty line here as EOF?

2022-05-20 16:45 UTC, Xtigyro commented on templates/puppetdb-serviceaccount.yaml
> +{{- end }}
Could you please add an empty line here as EOF?

2022-05-20 16:45 UTC, Xtigyro commented on templates/puppetserver-podsecuritypolicy.yaml
> +{{- end }}
Could you please add an empty line here as EOF?

2022-05-20 16:45 UTC, Xtigyro commented on templates/puppetserver-role.yaml
> +{{- end }}
Could you please add an empty line here as EOF?

2022-05-20 16:45 UTC, Xtigyro commented on templates/puppetserver-rolebinding.yaml
> +{{- end }}
Could you please add an empty line here as EOF?

2022-05-20 16:45 UTC, Xtigyro commented on templates/puppetserver-serviceaccount.yaml
> +{{- end }}
Could you please add an empty line here as EOF?

2022-05-23 07:25 UTC, davidphayanouvong commented
I fixed all recommendation and updated the changelog !

2022-05-24 08:28 UTC, davidphayanouvong commented
@Xtigyro I fixed all recommendations and updated the changelog!

2022-05-24 15:25 UTC, Xtigyro approved these changes
Thank you very much once more, @davidphayanouvong - this is a very nice PR!

2022-05-24 15:25 UTC, merged