Allow to change load balancer type for puppet master
puppetlabs/puppetserver-helm-chart pull request #133
Opened 2022-10-03 09:11 UTC by gmenuel

If compilers are not used the LoadBalancer type of the puppet master service was fixed to ClusterIP. This PR change this behaviour and re-allow to change the LoadBalancer type.

Closes: #132

2022-10-03 09:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=133) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetserver-helm-chart?pullRequest=133) it.</sub>

2022-10-03 15:19 UTC, Xtigyro requested changes
Thanks for the contribution, @gmenuel! 🥇

Could you please update the `CHANGELOG.md` following the same pattern for previous releases and bump the minor (not the bugfix) chart version in `Chart.yaml`?

Ah, yeah - finally, you might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)? 🥇

2022-10-04 07:33 UTC, gmenuel commented
Done, I've also fixed the changelog link and release date for the last release.

2022-10-04 12:03 UTC, Xtigyro approved these changes
Thank you, @gmenuel!

2022-10-04 12:03 UTC, merged