Fix annotations in puppetdb-pvc
puppetlabs/puppetserver-helm-chart pull request #149
Opened 2023-01-17 08:22 UTC by akiryushin

2023-01-17 08:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=149) <br/>All committers have signed the CLA.

2023-01-17 09:44 UTC, davidphay commented
Thanks for the PR! can you please sign the CLA & bump the `Chart.yaml` version, update the `changelog.md` & You might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)?

2023-01-17 11:27 UTC, Xtigyro requested changes, later dismissed
Thanks for the contribution, @akiryushin! 🥇

Could you please update the `CHANGELOG.md` following the same pattern for previous releases and bump the bugfix chart version in `Chart.yaml`?

Ah, yeah - finally, you might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)? 🥇

2023-01-17 18:36 UTC, akiryushin commented
Done

2023-01-18 10:44 UTC, davidphay commented
I add 2 suggestions, after that it will be ok for me.

2023-01-26 08:28 UTC, davidphay commented
@akiryushin Hello, you have to rebase your branch, many commit has been added.

2023-01-27 11:35 UTC, akiryushin commented
@davidphay done

2023-01-27 12:05 UTC, davidphay commented
@akiryushin in `templates/puppetserver-pvc.yaml` there still an issue.

2023-01-27 12:59 UTC, akiryushin commented
@davidphay sorry, didn't see. Check it

2023-01-27 13:09 UTC, davidphay approved these changes
Thanks @akiryushin !

2023-01-27 13:09 UTC, davidphay commented on CHANGELOG.md
> +## [v7.1.1](https://github.com/puppetlabs/puppetserver-helm-chart/tree/v7.0.0) (2023-01-xx)
```suggestion
## [v7.1.1](https://github.com/puppetlabs/puppetserver-helm-chart/tree/v7.2.2) (2023-01-18)
```

Please update the date here

2023-01-27 13:09 UTC, davidphay commented on templates/puppetserver-pvc.yaml
> +    {{ toYaml .Values.storage.annotations | indent 4 }}
```suggestion
    {{ toYaml .Values.storage.annotations | nindent 4 }}
```

2023-01-27 13:09 UTC, davidphay commented on templates/puppetserver-pvc.yaml
> +    {{ toYaml .Values.storage.annotations | indent 4 }}
@akiryushin Here it's not fixed

2023-01-27 13:10 UTC, merged

2023-01-27 13:17 UTC, akiryushin commented on CHANGELOG.md
> +## [v7.1.1](https://github.com/puppetlabs/puppetserver-helm-chart/tree/v7.0.0) (2023-01-xx)
late?