feat(r10k): parametrize the command line for r10k
puppetlabs/puppetserver-helm-chart pull request #180
Opened 2023-07-11 13:32 UTC by JGodin-C2C

# What:
Allows the parametrization of the command line for the r10k pods.

# Why:
This allows a "manual" launch of the r10k command, usefull for exemple for a CI.

2023-07-12 07:53 UTC, JGodin-C2C commented
Added documentation of the new parameters as it was missing.

2023-07-12 08:11 UTC, davidphay commented
Thanks @JGodin-C2C ! it's ok for me, can you bump the Chart and update the Changelog please ?

2023-07-12 09:59 UTC, JGodin-C2C commented
Okay ! I have done, the thing :dramatic_look:

2023-07-13 06:00 UTC, davidphay requested changes

2023-07-13 06:00 UTC, davidphay commented on CHANGELOG.md
> +## [v8.0.1](https://github.com/puppetlabs/puppetserver-helm-chart/tree/v8.0.1) (2023-07-12)
Please bump the minor version `8.1.0`

2023-07-13 06:00 UTC, davidphay commented on Chart.yaml
> +version: 8.0.1
Please bump the minor version `8.1.0`

2023-07-13 08:41 UTC, davidphay approved these changes

2023-07-13 08:41 UTC, merged