Update Chart version
puppetlabs/puppetserver-helm-chart pull request #209
Opened 2024-03-06 13:56 UTC by ke5C2Fin

2024-03-06 13:58 UTC, ke5C2Fin commented
Done, @Xtigyro 
Unless I should update the tests?

2024-03-06 16:49 UTC, Xtigyro requested changes

2024-03-06 16:49 UTC, Xtigyro commented on CHANGELOG.md
> +## [v9.2.1](https://github.com/puppetlabs/puppetserver-helm-chart/tree/v9.2.1) (2024-04-06)
Not needed, please remove it.

2024-03-06 16:49 UTC, Xtigyro commented on Chart.yaml
> +version: 9.2.1
Should be `9.2.0`.

2024-03-07 06:58 UTC, ldaneliukas commented
@ke5C2Fin please do update the tests so that the CI checks aren't failing. You can do that by running `helm unittest . -u`.

2024-03-07 14:28 UTC, Xtigyro approved these changes

2024-03-07 14:28 UTC, Xtigyro commented
@ke5C2Fin @ldaneliukas Thank you both! 🥇

2024-03-07 14:28 UTC, merged