Fix permission issue and template issues
puppetlabs/puppetserver-helm-chart pull request #216
Opened 2024-04-08 21:29 UTC by johannagnarsson

First two changes will fix the puppetdb-preinit container from failing with a `mkdir: cannot create directory ‘/opt/puppetlabs/server/data/puppetdb/certs’: Permission denied` when `puppetmasters.preGeneratedCertsJob.enabled` is set to true. 
 as it tries to run as non-root by default even if it's disabled.
Second change fixes a broken reference to the puppetmaster-preinstall configmap which prevents the server from starting up correctly when `puppetmasters.preGeneratedCertsJob.enabled` is set to true.

2024-04-08 21:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=216) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=216) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetserver-helm-chart?pullRequest=216) it.</sub>

2024-04-08 23:06 UTC, Xtigyro approved these changes

2024-04-08 23:07 UTC, Xtigyro requested changes
@johannagnarsson Thank you for the contribution! 

Could you please update the `CHANGELOG.md` and bump the bugfix chart version in `Chart.yaml`?

2024-04-09 13:39 UTC, johannagnarsson commented
Changes made as requested! @Xtigyro

2024-04-09 18:07 UTC, Xtigyro approved these changes
@johannagnarsson Thank you! 🥇

2024-04-09 18:09 UTC, Xtigyro requested changes
@johannagnarsson One more thing (which I initially forgot, apologies).

Could you please also run: 
```
helm unittest . -u
```

2024-04-09 18:28 UTC, johannagnarsson commented
Result below, I do see the same fails on the upstream repo as well. 

### Chart [ puppetserver ] .

 FAIL  test jmx serviceMonitor creation	tests/jmx-servicemonitor_test.yaml
	- should fail if monitoring.coreos.com/v1 api is not available

		- asserts[0] `failedTemplate` fail
			Template:	puppetserver/templates/jmx-servicemonitor.yaml
			DocumentIndex:	0
			Expected to equal:
				ERROR: You have to deploy monitoring.coreos.com/v1 first
			Actual:
				You have to deploy monitoring.coreos.com/v1 first

 PASS  test puppet puppet volume creation	tests/puppetdb-pvc_test.yaml
 FAIL  test puppetdb serviceMonitor creation	tests/puppetdb-servicemonitor_test.yaml
	- should fail if monitoring.coreos.com/v1 api is not available

		- asserts[0] `failedTemplate` fail
			Template:	puppetserver/templates/puppetdb-servicemonitor.yaml
			DocumentIndex:	0
			Expected to equal:
				ERROR: You have to deploy monitoring.coreos.com/v1 first
			Actual:
				You have to deploy monitoring.coreos.com/v1 first

 PASS  test puppetdb networkpolicy creation	tests/puppetdb.networkpolicy_test.yaml
 PASS  test puppet ca volume creation	tests/puppetserver-ca-pvc_test.yaml
 FAIL  test puppet code volume creation	tests/puppetserver-code-pvc_test.yaml
	- manifest should match snapshot

		- asserts[0] `matchSnapshot` fail
			Template:	puppetserver/templates/puppetserver-code-pvc.yaml

 FAIL  test puppetserver compilers statefulset creation	tests/puppetserver-compilers.deployment_test.yaml
	- manifest should match snapshot

		- asserts[0] `matchSnapshot` fail
			Template:	puppetserver/templates/hiera-configmap.yaml
			Template:	puppetserver/templates/r10k-code.configmap.yaml
			Template:	puppetserver/templates/r10k-hiera.configmap.yaml
			Template:	puppetserver/templates/update-crl-configmap.yaml

 PASS  test puppetserver (compilers) networkpolicy creation	tests/puppetserver-compilers.networkpolicy_test.yaml
 PASS  test puppetserver compilers podDisruptionBudget creation	tests/puppetserver-compilers.pdb_test.yaml
 FAIL  test puppetserver compilers statefulset creation	tests/puppetserver-compilers.statefulset_test.yaml
	- manifest should match snapshot

		- asserts[0] `matchSnapshot` fail
			Template:	puppetserver/templates/hiera-configmap.yaml
			Template:	puppetserver/templates/r10k-code.configmap.yaml
			Template:	puppetserver/templates/r10k-hiera.configmap.yaml
			Template:	puppetserver/templates/update-crl-configmap.yaml

 FAIL  test puppet data volume creation	tests/puppetserver-data-pvc_test.yaml
	- manifest should match snapshot

		- asserts[0] `matchSnapshot` fail
			Template:	puppetserver/templates/puppetserver-data-pvc.yaml

 PASS  test puppetserver (masters) networkpolicy creation	tests/puppetserver-masters.networkpolicy_test.yaml
 PASS  test puppetserver master podDisruptionBudget creation	tests/puppetserver-masters.pdb_test.yaml
 PASS  test puppet puppet volume creation	tests/puppetserver-pvc_test.yaml

Charts:      1 failed, 0 passed, 1 total
Test Suites: 6 failed, 8 passed, 14 total
Tests:       6 failed, 65 passed, 71 total
Snapshot:    12 passed, 12 total
Time:        334.573499ms

Error: plugin "unittest" exited with error

2024-04-09 22:53 UTC, Xtigyro approved these changes

2024-04-09 22:54 UTC, Xtigyro commented
@johannagnarsson That's fine. Thank you once more!

2024-04-09 22:54 UTC, merged