Change the order how env block is built
puppetlabs/puppetserver-helm-chart pull request #83
Opened 2021-04-21 19:02 UTC by erlonpinheiro

By using a newer puppetDB image, the puppetDB certificate and key path has changed and it is not possible to overwrite the variables responsible to configure that because these variables where defined on the template after the block that reads from value.yaml file.

By changing the order the values will still be coming from template but they will be able to be overwritten by those one added on values.yaml file (since Kubernetes consider the last one).

2021-04-21 19:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=83) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=83) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetserver-helm-chart?pullRequest=83) it.</sub>

2021-04-22 10:44 UTC, Xtigyro requested changes
Hey @erlonpinheiro 👋
Thank you for your contribution - it's appreciated! 💯

Could you please update the `CHANGELOG` and bump the chart version in `Chart.yaml`?
You might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)?

2021-04-22 16:25 UTC, erlonpinheiro commented
All requested changes were done.

2021-04-22 19:13 UTC, Xtigyro commented
@erlonpinheiro Awesome, man - thank you once more!

2021-04-22 19:14 UTC, Xtigyro approved these changes

2021-04-22 19:14 UTC, merged