update to new api version of ingress (v1.19+)
puppetlabs/puppetserver-helm-chart pull request #91
Opened 2021-07-21 17:07 UTC by h-phil

The current API version of ingress in use will be deprecated in version v1.22.
See the API deprecation guide: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

2021-07-21 17:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=91) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=91) before we can accept your contribution.<br/><hr/>**Philipp Hauswirth** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetserver-helm-chart?pullRequest=91) it.</sub>

2021-07-22 07:26 UTC, Xtigyro requested changes
Thanks for the contribution, @h-phil! 🥇 

Could you please update the Changelog and bump the minor chart version in `Chart.yaml`?

2021-07-22 10:49 UTC, Xtigyro approved these changes
Thank you!

2021-07-22 10:50 UTC, merged

2021-07-22 10:52 UTC, h-phil commented
@Xtigyro Thank you.